from .admin import Admin
from .card import Card
from .client import Client
from .crop import Crop
from .fertilizer import Fertilizer
from .lab import Lab
from .land import Land
from .lot import Lot
from .nutrients import Nutrients
from .optimal_range_age import OptimalRangeAge
from .price_fertilizer import PriceFertilizer
from .recomendation import Recomendation
from .user import User
