from .Admin import Admin
from .Card import Card
from .Client import Client
from .Crop import Crop
from .Fertilizer import Fertilizer
from .Lab import Lab
from .Land import Land
from .Lot import Lot
from .Nutrients import Nutrients
from .PriceFertilizer import PriceFertilizer
from .Recomendation import Recomendation
from .User import User
