from .base_controller import BaseController
from .card_controller import CardController
from .crop_controller import CropController
from .fertilizer_controller import FertilizerController
from .lab_controller import LabController
from .land_controller import LandController
from .nutrient_set_controller import NutrientSetController
from .ideal_controller import IdealController
from .recomendation_controller import RecomendationController
from .user_controller import UserController
